// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BibliotecaClassDiagram.BibliotecaClassDiagram;

/************************************************************/
/**
 * 
 */
public class Autor {
	/**
	 * Atributele clasei Autor
	 */
	
	/**
	 * Numele autorului
	 */
	private String nume;

	/**
	 * Prenumele autorului
	 */
	private String prenume;

	/**
	 * Telefonul autorului
	 */
	private String telefon;

	/**
	 * Email-ul autorului
	 */
	private String email;

	/**
	 * Data de nastere a autorului
	 */
	private String dataNastere;

	Autor(String nume, String prenume, String telefon, String email, String dataNastere) {
		this.nume = nume;
	}
	
	String getNume() {
		return this.nume;
	}
	
	String getPrenume() {
		return this.prenume;
	}
	
	String getTelefon() {
		return this.telefon;
	}
	
	String getEmail() {
		return this.email;
	}
	
	String getDataNastere() {
		return this.dataNastere;
	}
	
	public void afisare() {
		System.out.println("=====  Informatii despre autor =====");
		System.out.println("Nume si prenume: " + this.nume + " " + this.prenume);
		System.out.println("Telefon: " + this.telefon);
		System.out.println("Email: " + this.email);
		System.out.println("Data de nastere: " + this.dataNastere);
	}
};
