// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BibliotecaClassDiagram.BibliotecaClassDiagram;

/************************************************************/
/**
 * 
 */
public class Bibliotecar {
	/**
	 * Atributele unui bibliotecar
	 */
	private String nume;
	/**
	 * Numele bibliotecarului
	 */
	private String prenume;
	/**
	 * Prenumele bibliotecarului
	 */
	private String telefon;
	/**
	 * Telefonul bibliotecarului
	 */
	private String email;

	/**
	 * Email-ul bibliotecarului
	 */
	public void afisare() {
	}
};
