// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BibliotecaClassDiagram.BibliotecaClassDiagram;

import java.util.ArrayList;
import java.util.List;


/************************************************************/
/**
 * 
 */
public class Biblioteca {
	/**
	 * Atributele clasei Biblioteca
	 */
	
	/**
	 * Numarul de carti existente in biblioteca
	 */
	private int numarCarti;
	/**
	 * Numarul de carti disponibile (care pot fi imprumutate)
	 */
	private int numarCartiDisponibile;
	/**
	 * Numarul de carti care au fost imprumutate
	 */
	private int numarCartiImprumutate;
	/**
	 * Numarul de carti pierdute
	 */
	private int numarCartiPierdute;
	/**
	 * Lista cu toate cartile din biblioteca
	 */
	// private Carte[] carte;
	private List<Carte> carti = new ArrayList<>();
	/**
	 * Lista cu istoricul tuturor imprumuturilor
	 */
	// private Imprumut[] fisaimprumut;
	private List<Imprumut> fisaImprumut = new ArrayList<>();
	/**
	 * Lista cu cititorii inregistrati 
	 */
	// private Cititor[] cititor;
	private List<Cititor> cititori = new ArrayList<>();
	/**
	 * Lista cu toti autorii cartilor din biblioteca
	 */
	// private Autor[] autor;
	private List<Autor> autori = new ArrayList<>();

	/**
	 * 
	 * @param carte 
	 */
	
	Biblioteca(int numarCarti, int numarCartiDisponibile, int numarCartiImprumutate, int numarCartiPierdute, List<Carte> carti,
			List<Imprumut> fisaImprumut, List<Cititor> cititori, List<Autor> autori) {
		this.numarCarti = numarCarti;
		this.numarCartiDisponibile = numarCartiDisponibile;
		this.numarCartiImprumutate = numarCartiImprumutate;
		this.numarCartiPierdute = numarCartiPierdute;
		this.carti = carti;
		this.fisaImprumut = fisaImprumut;
		this.cititori = cititori;
		this.autori = autori;
	}
	
	int getNumarCarti() {
		return this.numarCarti;
	}
	
	int getNumarCartiDisponibile() {
		return this.numarCartiDisponibile;
	}
	
	int getNumarCartiImprumutate() {
		return this.numarCartiImprumutate;
	}
	
	int getNumarCartiPierdute() {
		return this.numarCartiPierdute;
	}
	
	List<Carte> getCarti() {
		return this.carti;
	}
	
	List<Imprumut> getDetaliiImprumut() {
		return this.fisaImprumut;
	}
	
	List<Cititor> getCititori() {
		return this.cititori;
	}
	
	List<Autor> getAutori() {
		return this.autori;
	}
	
	public void adaugaCarte(Carte carte) {
	}

	/**
	 * 
	 * @param carte 
	 */
	public void stergeCarte(Carte carte) {
	}

	/**
	 * 
	 * @param cititor 
	 */
	public void adaugaCititor(Cititor cititor) {
	}

	/**
	 * 
	 * @param fisa 
	 */
	public void adaugaImprumut(Imprumut fisa) {
	}

	/**
	 * 
	 * @param fisa 
	 */
	public void stergeImprumut(Imprumut fisa) {
	}

	/**
	 * 
	 * @param cititor 
	 */
	public void stergeCititor(Cititor cititor) {
	}
};
