// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BibliotecaClassDiagram.BibliotecaClassDiagram;

/************************************************************/
/**
 * 
 */
public class Carte {
	/**
	 * 
	 */
	private int carteID;
	/**
	 * 
	 */
	private String titlu;
	/**
	 * 
	 */
	private Editura editura;
	/**
	 * 
	 */
	private Limba limba;
	/**
	 * 
	 */
	private int numarPagini;
	/**
	 * 
	 */
	private int anAparitie;
	/**
	 * 
	 */
	private int numarExemplare;
	/**
	 * 
	 */
	private GenCarte genCarte;
	/**
	 * 
	 */
	private Autor[] autor;

	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 * @param carteID 
	 */
	public void adaugareExemplar(int carteID) {
	}

	/**
	 * 
	 * @param carteID 
	 */
	public void stergereExemplar(int carteID) {
	}
};
