// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BibliotecaClassDiagram.BibliotecaClassDiagram;

/************************************************************/
/**
 * 
 */
public class Cititor {
	/**
	 * 
	 */
	private int cititorID;
	/**
	 * 
	 */
	private String nume;
	/**
	 * 
	 */
	private String prenume;
	/**
	 * 
	 */
	private String dataNastere;
	/**
	 * 
	 */
	private String telefon;
	/**
	 * 
	 */
	private String email;
	/**
	 * 
	 */
	private String adresa;
	/**
	 * 
	 */
	private String CNP;
	/**
	 * 
	 */
	private Imprumut[] imprumut;

	/**
	 * 
	 */
	public void afisare() {
	}
};
