// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BibliotecaClassDiagram.BibliotecaClassDiagram;

/************************************************************/
/**
 * 
 */
public class Imprumut {
	/**
	 * 
	 */
	private String dataImprumut;
	/**
	 * 
	 */
	private String dataReturnare;
	/**
	 * 
	 */
	private String dataLimitaCarte;
	/**
	 * 
	 */
	private Bibliotecar bibliotecar;
	/**
	 * 
	 */
	private Carte[] carte;
	/**
	 * 
	 */
	private Carte Carti;

	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 * @param dataLimitaCarte 
	 */
	public void depasireTermen(String dataLimitaCarte) {
	}
};
