// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BibliotecaClassDiagram.BibliotecaClassDiagram;

/************************************************************/
/**
 * 
 */
public class Autor {

	private String nume; //Numele autorului
	private String prenume; //Prenumele autorului
	private String telefon; //Telefonul autorului
	private String email; //Email-ul autorului
	private String dataNastere; //Data de nastere a autorului

	public Autor(String nume, String prenume, String telefon, String email, String dataNastere) {
		this.nume = nume;
		this.prenume = prenume;
		this.telefon = telefon;
		this.email = email;
		this.dataNastere = dataNastere;
	}
	
	String getNume() {
		return this.nume;
	}
	
	String getPrenume() {
		return this.prenume;
	}
	
	String getTelefon() {
		return this.telefon;
	}
	
	String getEmail() {
		return this.email;
	}
	
	String getDataNastere() {
		return this.dataNastere;
	}

	public void setNume(String nume) {
		this.nume = nume;
	}

	public void setPrenume(String prenume) {
		this.prenume = prenume;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public void setDataNastere(String dataNastere) {
		this.dataNastere = dataNastere;
	}

	public void afisare() {
		System.out.println("=====  Informatii despre autor =====");
		System.out.println("Nume si prenume: " + this.nume + " " + this.prenume);
		System.out.println("Telefon: " + this.telefon);
		System.out.println("Email: " + this.email);
		System.out.println("Data de nastere: " + this.dataNastere);
	}
};
