// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BibliotecaClassDiagram.BibliotecaClassDiagram;

/************************************************************/
/**
 * 
 */
public class Bibliotecar {

	private String nume; // Numele bibliotecarului
	private String prenume; // Prenumele bibliotecarului
	private String telefon; // Telefonul bibliotecarului
	private String email; //Email-ul bibliotecarului

	public Bibliotecar(String nume, String prenume, String telefon, String email) {
		this.nume = nume;
		this.prenume = prenume;
		this.telefon = telefon;
		this.email = email;
	}
	
	String getNume() {
		return this.nume;
	}

	String getPrenume() {
		return this.prenume;
	}
	
	String getTelefon() {
		return this.telefon;
	}
	
	String getEmail() {
		return this.email;
	}

	public void setNume(String nume) {
		this.nume = nume;
	}

	public void setPrenume(String prenume) {
		this.prenume = prenume;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public void afisare() {
		System.out.println("=====  Informatii despre bibliotecar =====");
		System.out.println("Nume si prenume: " + this.nume + " " + this.prenume);
		System.out.println("Telefon: " + this.telefon);
		System.out.println("Email: " + this.email);
	}

	public void aplicaPenalizare(Cititor cititor) {
		cititor.aplicaPenalizare();
	}
};
