// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BibliotecaClassDiagram.BibliotecaClassDiagram;

import java.util.ArrayList;
import java.util.List;

/************************************************************/
/**
 * 
 */
public class Carte {

	private int carteID;
	private String titlu;
	private Editura editura;
	private Limba limba;
	private int numarPagini;
	private int anAparitie;
	private int numarExemplare;
	private GenCarte genCarte;
	private List<Autor> autori = new ArrayList<>();

	public Carte(int carteID, String titlu, Editura editura, Limba limba, int numarPagini, 
			int anAparitie, int numarExemplare, GenCarte genCarte, List<Autor> autori) {
		this.carteID = carteID;
		this.titlu = titlu;
		this.editura = editura;
		this.limba = limba;
		this.numarPagini = numarPagini;
		this.anAparitie = anAparitie;
		this.numarExemplare = numarExemplare;
		this.genCarte = genCarte;
		this.autori = autori;
	}
	
	int getCarteID() {
		return this.carteID;
	}
	
	String getTitlu() {
		return this.titlu;
	}
	
	Editura getEditura() {
		return this.editura;
	}
	
	Limba getLimba() {
		return this.limba;
	}
	
	int getNrPagini() {
		return this.numarPagini;
	}
	
	int getAnAparitie() {
		return this.anAparitie;
	}
	
	int getNrExemplare() {
		return this.numarExemplare;
	}
	
	GenCarte getGenCarte() {
		return this.genCarte;
	}
	
	List<Autor> getAutori() {
		return this.autori;
	}

	public void afisare() {
		System.out.println("===== Informatii despre carte =====");
		System.out.println("Id carte:" + this.carteID +"\nTitlu: "+ this.titlu+ "\nEditura: "+ this.editura);
		System.out.println("Limba: "+ this.limba + "\nNumar pagini: "+this.numarPagini );
		System.out.println("An aparitie: "+this.anAparitie + "\nNumar exemplare: "+ this.numarExemplare);
		System.out.println("Gen: " + this.genCarte);
		for(Autor a : autori)
			a.afisare();
	}
};
