// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BibliotecaClassDiagram.BibliotecaClassDiagram;

import java.util.ArrayList;
import java.util.List;

/************************************************************/
/**
 * 
 */
public class Cititor {

	private int cititorID;
	private String nume;
	private String prenume;
	private String dataNastere;
	private String telefon;
	private String email;
	private String adresa;
	private String CNP;
	static private int punctePenalizare = 0;
	private List<Imprumut> imprumuturi  = new ArrayList<>();

	public Cititor(int cititorID, String nume, String prenume, String dataNastere, 
			String telefon, String email, String adresa, String CNP, List<Imprumut> imprumuturi) {
		this.cititorID = cititorID;
		this.nume = nume;
		this.prenume = prenume;
		this.dataNastere = dataNastere;
		this.telefon = telefon;
		this.email = email;
		this.adresa = adresa;
		this.CNP = CNP;
		this.imprumuturi = imprumuturi;
		this.punctePenalizare = 0;
	}

	public int getCititorID() {
		return cititorID;
	}

	public Cititor getCititorID(List<Cititor> list, int cititorID) {


		return null;
	}

	public void setCititorID(int cititorID) {
		this.cititorID = cititorID;
	}

	public String getNume() {
		return nume;
	}

	public void setNume(String nume) {
		this.nume = nume;
	}

	public String getPrenume() {
		return prenume;
	}

	public void setPrenume(String prenume) {
		this.prenume = prenume;
	}

	public String getDataNastere() {
		return dataNastere;
	}

	public void setDataNastere(String dataNastere) {
		this.dataNastere = dataNastere;
	}

	public String getTelefon() {
		return telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAdresa() {
		return adresa;
	}

	public void setAdresa(String adresa) {
		this.adresa = adresa;
	}

	public String getCNP() {
		return CNP;
	}

	public void setCNP(String CNP) {
		this.CNP = CNP;
	}

	public static int getPunctePenalizare() {
		return punctePenalizare;
	}

	public static void setPunctePenalizare(int punctePenalizare) {
		Cititor.punctePenalizare = punctePenalizare;
	}

	public List<Imprumut> getImprumuturi() {
		return imprumuturi;
	}

	public void setImprumuturi(List<Imprumut> imprumuturi) {
		this.imprumuturi = imprumuturi;
	}

	public void afisare() {
		System.out.println("=====  Informatii despre cititor =====");
		System.out.println("Nume si prenume: " + this.nume + " " + this.prenume);
		System.out.println("Data nastere: " + this.dataNastere);
		System.out.println("Telefon: " + this.telefon);
		System.out.println("Email: " + this.email);
		System.out.println("Adresa: " + this.adresa);
		System.out.println("CNP: " + this.CNP);
		System.out.println("Puncte de penalizare: " + this.punctePenalizare);
		System.out.println("Imprumuturi:");
		
		for (int i = 0; i < imprumuturi.size(); i++) {
			imprumuturi.get(i).afisare();
		}
	}

	public void aplicaPenalizare() {

		this.punctePenalizare++;
	}
};