// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BibliotecaClassDiagram.BibliotecaClassDiagram;

/************************************************************/
/**
 * 
 */
public enum Editura {
	/**
	 * 
	 */
	Art,
	/**
	 * 
	 */
	Litera,
	/**
	 * 
	 */
	Humanitas,
	/**
	 * 
	 */
	Corint,
	/**
	 * 
	 */
	Paralela45,
	/**
	 * 
	 */
	Booklet,
	/**
	 * 
	 */
	RAO;
};
