// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BibliotecaClassDiagram.BibliotecaClassDiagram;

/************************************************************/
/**
 * 
 */
public enum GenCarte {
	/**
	 * 
	 */
	Comedie,
	/**
	 * 
	 */
	Drama,
	/**
	 * 
	 */
	SF,
	/**
	 * 
	 */
	Romance,
	/**
	 * 
	 */
	Politist,
	/**
	 * 
	 */
	Horror,
	/**
	 * 
	 */
	Actiune,
	/**
	 * 
	 */
	Folclor,
	/**
	 * 
	 */
	Copii;
};
