// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BibliotecaClassDiagram.BibliotecaClassDiagram;

/************************************************************/
/**
 * 
 */
public enum Limba {
	/**
	 * 
	 */
	Romana,
	/**
	 * 
	 */
	Engleza,
	/**
	 * 
	 */
	Franceza,
	/**
	 * 
	 */
	Spaniola,
	/**
	 * 
	 */
	Germana,
	/**
	 * 
	 */
	Italiana,
	/**
	 * 
	 */
	Rusa;
};
